const pack = {features, creatures}

export default pack

var features, creatures

pack.features =   // elements, materials, properties and features for creatures
  `able,acid,aether,agitated,air,all-seeing,amazing,amber,ancient,angelic,angry,
  anxious,apt,arcane,armored,arrogant,ash,bald,battle,beautiful,big,bitter,
  black,blade,blazing,blind,blink,blood,bloody,bold,bolt,bone,book,boring,
  brass,brave,brittle,bronze,burning,calming,caped,carbon,carrion,cave,chained,
  chemical,chosen,chromatic,chrome,chrystal,clever,cloaked,cloud,cohesion,cold,
  copper,craft,crazy,cream,crooked,crude,crying,cryo,cunning,curious,cursed,
  damned,dangerous,dark,deadwood,death,desaturated,destructive,devoted,diamond,
  dim,dimentional,dirty,disturbed,divine,drama,dream,drunk,dubious,dumb,dust,
  eager,earth,ebony,eerie,elastic,elder,eldrich,electric,elusive,emerald,
  emerging,ender,energized,entropy,ether,evil,exalted,fabled,fairy,faithful,
  fallen,false,famed,fancy,fearful,fearless,feather,ferocious,fiber,fierce,
  fiery,fire,flash,flawed,flower,fluffy,fog,foil,force,forest,forgotten,foul,
  frantic,friendly,fun,funky,funny,fur,furry,future,ghost,giant,gifted,glacial,
  glade,glass,glorified,golden,good,gore,gorgeous,grass,grave,gray,green,grim,
  grinning,gross,hairy,halo,happy,hazy,heat,hectic,hell,helpful,helpless,high,
  highborn,holy,honourable,hopeful,horadric,horrible,huge,hungry,ice,immortal,
  impalpable,imperfect,impure,infected,infectious,infernal,ink,insane,
  insidious,intangible,invisible,ionic,iridium,iron,jade,jagged,juicy,kinky,
  lake,laughing,lava,leather,life,light,lightning,liquid,little,lovely,lucky,
  mad,magic,magma,magnetic,marble,matter,maze,meat,mech,mechanical,meta,metal,
  meteoric,mindless,mirror,mist,moon,morphic,mountain,mud,mythic,naked,natural,
  necro,neon,nervous,night,nimble,noble,notorious,obsidian,odd,oil,old,ominous,
  omnipotent,omniscient,onyx,opal,orange,painted,paper,paradox,pearl,perfect,
  phantom,phasing,pink,plain,playful,poison,precursor,prime,prominent,promised,
  psy,pulp,punctual,pure,quartz,quiet,raging,rainbow,random,rattle,ravenous,
  raw energy,razor,reality,red,restless,rift,river,rot,rubber,ruby,sacred,
  saint,salt,salty,sand,sane,sapphire,savage,scarred,scary,screaming,screamy,
  script,sea,secret,serenity,shameless,shapeless,sharp,shining,shy,silent,silk,
  silver,sinister,sky,sly,smart,smoke,snake,snow,sonic,soul,sour,space,spark,
  spectral,spicy,spiked,spirit,spooky,star,static,steam,steel,stone,storm,
  story,strange,sturdy,subtle,sugar,sulphur,sun,swamp,sweet,talkative,tall,
  tearful,terrible,the first,the last,thunder,time,timid,tin,tiny,topaz,
  torchwood,troubled,true,twin,twisted,uber,unbreakable,uncanny,unchained,
  undead,uneasy,unnerving,vacant,vague,vapor,venom,vermillion,vicious,vile,
  violent,vivid,voiceless,void,wandering,war,warped,water,wax,weird,white,wild,
  wind,winged,wire,wise,wishful,wonder,wood,young,zealous`.split(/,\s*/)

pack.creatures =    // creatures, characters and enitites for fantasy games
  `acolyte,aid,alp,amazon,angel,ape,apostate,apostle,apprentice,arach,archer,
  archmage,armor,assassin,avatar,badger,bannerman,banshee,bard,barghest,
  basilisk,bat,beam,bear,bearer,beast,beatle,behemoth,being,bender,berserker,
  bird,blade,bogeyman,bogle,box,boy,breaker,breath,bruiser,brute,bruxa,bug,
  bull,bullvore,bunny,carbuncle,cat,cemetaur,censor,centaur,centicore,cerberus,
  champion,changeling,charmer,chimaera,chimera,cleric,clerk,cloud,cobra,
  colossus,confessor,conjuror,construct,contraption,copycat,crab,creature,
  creeper,crone,cube,cultist,cyclops,daemon,demicat,demidog,demigod,devourer,
  disciple,dog,dozen,draconid,dragon,drake,draugr,drow,drowner,drude,dryad,
  dude,duke,dwarf,dweller,eagle,eater,edge,effigy,efreet,ekhidna,elemental,elf,
  elfin,embodiment,enchanter,endrega,ent,essence,ettin,eye,fairy,familiar,
  fantasy,faun,fetch,fiend,fighter,figure,figurine,fist,fleder,foglet,follower,
  form,fox,freak,frightener,frog,fungus,fury,gargoyle,garkain,genie,ghost,
  ghoul,giant,girl,glutton,gnome,goblin,god,godling,golem,golyath,gorgon,
  graveir,gremlin,griffin,grigg,grin,guard,guardian,guide,gulon,hag,halfling,
  harpy,hawk,hero,hob,horror,hound,howler,hunter,husk,hydra,hym,ibis,idol,
  illusion,imp,incubus,insectoid,jellyfish,jinn,juggernaut,kabouter,kami,
  katakan,kayran,keeper,kernun,kid,kikimora,kin,king,knight,knocker,kobold,
  kraken,lady,lamia,lancer,leech,leprechaun,leshen,leviathan,lich,lieutenant,
  lizard,lord,lurker,lutin,lynx,madness,mage,maggot,maiden,mamune,man,
  manticore,mara,mare,master,medusa,menace,merc,midget,mimic,minion,minotaur,
  minx,misfortune,monger,monk,monkey,monster,moss,moth,muse,mutant,myling,
  nadir,naga,nagual,nargun,nekker,nix,nomad,nonsense,numen,nymph,oak,octopus,
  ogre,one,oni,ooze,orc,organism,ork,owl,ox,paladin,paradox,pard,pegasus,peng,
  pilgrim,pillar,pirate,pixie,platypus,power,presence,priest,priestess,prince,
  princess,prism,problem,projection,prophet,puck,punk,python,qilin,queen,
  raccoon,raider,ranger,raptor,rat,raven,reader,reaper,reflection,renegade,
  replica,reptile,repulsor,rider,roc,rogue,romantic,rover,runner,ryu,sage,
  satyr,scamp,scout,scurver,sentinel,seraph,serpent,servant,servo,shade,shadow,
  shaitan,shaman,shape,shifter,shit,shooter,shrieker,sigbin,singer,siren,
  skeleton,slayer,slime,smile,smuggler,snake,sorcerer,soul,spark,spawn,spectre,
  spellweaver,sphere,sphinx,spider,spirit,spriggan,sprite,stalker,star,steed,
  storm,strider,striga,striker,strix,substance,succubus,swan,sylph,taunter,
  taurus,templar,tennin,thief,tigris,titan,toad,totem,traitor,trapper,tree,
  trickster,trinity,triton,troll,trow,truth,turtle,twin,uma,umbra,unicorn,upin,
  urchin,vampire,vanara,vesper,vessel,vibria,viking,villain,vine,visionary,
  voice,vulture,walker,wall,wanderer,warden,warg,warlock,warrior,wasp,wave,
  welkin,werecat,werewolf,widow,wisp,witch,witcher,wizard,wolf,woman,worm,
  wraith,wrath,wurm,wyrm,wyvern,yale,yanari,yeti,zephyr,zeugl,zombie`
    .split(/,\s*/)
